# Generated by Django 5.0.2 on 2024-02-24 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ratings',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
