# Generated by Django 5.0.2 on 2024-02-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_alter_doctor_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ratings',
            field=models.IntegerField(),
        ),
    ]
