# Generated by Django 5.0.2 on 2024-02-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_alter_doctor_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('app_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapp.doctor')),
            ],
        ),
    ]
