# Generated by Django 5.0.2 on 2024-02-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
