# Generated by Django 5.0.2 on 2024-02-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0006_alter_doctor_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
