# Generated by Django 5.0.2 on 2024-02-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0007_alter_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
