# Generated by Django 5.0.2 on 2024-02-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0013_remove_doctor_last_login_doctor_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='auth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
