# Generated by Django 5.0.2 on 2024-02-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0015_doctor_profile_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(blank=True, default='doctorProfilePhoto/avatar.svg', null=True, upload_to='images/Doctor_profile_photo'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
